### ISSUE TITLE
Cannot view the demo properly

### ISSUE THREAD

**Issue by jaidevanoop** [victormiguez/Meteor-Recipes#1]
The sidebar and the rest of the application does not load
![screenshot from 2015-12-06 19 00 44](https://cloud.githubusercontent.com/assets/7580385/11613598/9770cc60-9c4c-11e5-8406-34ac0a447229.png)

**Comment by victormiguez** [comment]
Thanks for the feedback, now as long as you are logged in, you can see the sidebar.
Fixed [here](https://github.com/victormiguez/Meteor-Recipes/commit/d1d270bb0ecb506c3f5a4a5b1c2e49ab7bf05f6d).
